/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiaryEntryTypeRequest } from './diaryEntryTypeRequest';


export interface CreateDiaryEntryRequest { 
    diaryEntryType: DiaryEntryTypeRequest;
    /**
     * User ID
     */
    userId?: string;
    /**
     * Display Date
     */
    displayDate: string;
    /**
     * Meta Data
     */
    metaData: object;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
}

