/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiaryEntryAssignmentView } from './diaryEntryAssignmentView';
import { DiaryEntryTypeRequest } from './diaryEntryTypeRequest';


export interface CreateDiaryEntryAssignmentRequest { 
    /**
     * The role ID.
     */
    roleId: string;
    diaryEntryType: DiaryEntryTypeRequest;
    diaryEntryAssignmentView: DiaryEntryAssignmentView;
}

