/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiaryEntryReminderResponse } from './diaryEntryReminderResponse';


export interface CreateReminder200Response { 
    data?: Array<DiaryEntryReminderResponse>;
    success?: boolean;
    error?: object;
}

