/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DiaryEntryReminderResponse { 
    /**
     * Diary Entry Reminder Id
     */
    diaryEntryReminderId: string;
    /**
     * User Id
     */
    userId: string;
    /**
     * Remind At
     */
    remindAt: string;
    /**
     * Current count of reminders for this diary entry & user.
     */
    count: number;
}

