/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DiaryEntryTypeCodeNames = 'reservationExpires' | 'leaseEffectiveDate' | 'leaseExpiryDate' | 'reservationStarts' | 'task' | 'spaceReservationStarts' | 'spaceReservationExpires' | 'leaseSigned' | 'leaseMoveOutCreated';

export const DiaryEntryTypeCodeNames = {
    ReservationExpires: 'reservationExpires' as DiaryEntryTypeCodeNames,
    LeaseEffectiveDate: 'leaseEffectiveDate' as DiaryEntryTypeCodeNames,
    LeaseExpiryDate: 'leaseExpiryDate' as DiaryEntryTypeCodeNames,
    ReservationStarts: 'reservationStarts' as DiaryEntryTypeCodeNames,
    Task: 'task' as DiaryEntryTypeCodeNames,
    SpaceReservationStarts: 'spaceReservationStarts' as DiaryEntryTypeCodeNames,
    SpaceReservationExpires: 'spaceReservationExpires' as DiaryEntryTypeCodeNames,
    LeaseSigned: 'leaseSigned' as DiaryEntryTypeCodeNames,
    LeaseMoveOutCreated: 'leaseMoveOutCreated' as DiaryEntryTypeCodeNames
};

