/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DiaryEntryAssignmentViewCodeNames = 'calendar';

export const DiaryEntryAssignmentViewCodeNames = {
    Calendar: 'calendar' as DiaryEntryAssignmentViewCodeNames
};

