/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiaryEntryAssignmentViewCodeNames } from './diaryEntryAssignmentViewCodeNames';


export interface DiaryEntryAssignmentView { 
    /**
     * Diary Entry Assignment View Id.
     */
    diaryEntryAssignmentViewId: number;
    codeName: DiaryEntryAssignmentViewCodeNames;
    /**
     * Display name of the diary entry assignment view.
     */
    displayName: string;
}
export namespace DiaryEntryAssignmentView {
}


