/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiaryEntryAssignmentView } from './diaryEntryAssignmentView';
import { DiaryEntryTypeResponse } from './diaryEntryTypeResponse';


export interface DiaryEntryAssignmentResponse { 
    /**
     * Diary Entry Assignment Id
     */
    diaryEntryAssignmentId: string;
    /**
     * Organization Id
     */
    orgId: string;
    /**
     * Site Id
     */
    siteId: string;
    /**
     * The role ID.
     */
    roleId: string;
    diaryEntryType: DiaryEntryTypeResponse;
    diaryEntryAssignmentView: DiaryEntryAssignmentView;
}

