/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiaryEntryTypeResponse } from './diaryEntryTypeResponse';


export interface DiaryEntryResponse { 
    /**
     * Diary Entry Id
     */
    diaryEntryId: string;
    /**
     * Organization Id
     */
    orgId: string;
    /**
     * Site Id
     */
    siteId: string;
    /**
     * User ID
     */
    userId: string | null;
    diaryEntryType: DiaryEntryTypeResponse;
    /**
     * Display Date
     */
    displayDate: string;
    /**
     * Meta Data
     */
    metaData: object;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Whether a diary entry is actioned
     */
    isActioned: boolean;
    /**
     * Whether a diary entry is read
     */
    isRead: boolean;
    /**
     * Reminder info
     */
    reminderInfo: object | null;
}

