/**
 * ManageSpace Diary API
 * ManageSpace Diary API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateDiaryEntryRequest { 
    /**
     * Mark a diary entry as actioned
     */
    isActioned?: boolean;
    /**
     * Mark a diary entry as read/unread
     */
    isRead?: boolean;
}

